// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieStore.Data;

namespace MovieStore.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200508155238_3migration")]
    partial class _3migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "02ca419c-4868-4f03-9b0f-8f8a4dd4a564",
                            ConcurrencyStamp = "d9749efc-4535-40e6-a320-f94d4beefb5b",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "02ca419c-4868-4f03-9b0f-8f8a4dd4a565",
                            ConcurrencyStamp = "9f4f4630-8488-48a7-a6e1-5e9dce981561",
                            Name = "editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = "02ca419c-4868-4f03-9b0f-8f8a4dd4a566",
                            ConcurrencyStamp = "1e5db413-4326-40e9-990c-beeb1af0667e",
                            Name = "guest",
                            NormalizedName = "GUEST"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "02ca419c-4868-4f03-9b0f-8f8a4dd4a564",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "482c714d-ef91-4281-8f23-c88a9b257f8c",
                            Email = "admin@onlinemoviestore.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ONLINEMOVIESTORE.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEI1WH45FjYiJDMHK94KRp9H1qCvUdPmOq7D7nLdp5ScYtUhzk/M0Syj5zBn8gAqjIg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "02ca419c-4868-4f03-9b0f-8f8a4dd4a564",
                            RoleId = "02ca419c-4868-4f03-9b0f-8f8a4dd4a564"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MovieStore.Data.Entities.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<bool>("Popularity")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Steven Spielberg",
                            Popularity = true
                        },
                        new
                        {
                            Id = 2,
                            Name = "Martin Scorsese",
                            Popularity = true
                        },
                        new
                        {
                            Id = 3,
                            Name = "Joe Russo",
                            Popularity = false
                        },
                        new
                        {
                            Id = 4,
                            Name = "Christopher Nolan",
                            Popularity = true
                        },
                        new
                        {
                            Id = 5,
                            Name = "Quentin Tarantino",
                            Popularity = true
                        },
                        new
                        {
                            Id = 6,
                            Name = "Richard Linklater",
                            Popularity = false
                        },
                        new
                        {
                            Id = 7,
                            Name = "Denis Villeneuve",
                            Popularity = false
                        },
                        new
                        {
                            Id = 8,
                            Name = "David Fincher",
                            Popularity = false
                        },
                        new
                        {
                            Id = 9,
                            Name = " Ron Clements",
                            Popularity = true
                        });
                });

            modelBuilder.Entity("MovieStore.Data.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Classics"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Crime & Thrillers"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Documentary"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Sci - Fi"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Musical"
                        });
                });

            modelBuilder.Entity("MovieStore.Data.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Budget")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DirectorID")
                        .HasColumnType("int");

                    b.Property<string>("DirectorName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.Property<string>("GenreName")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("PhotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PriceForBuy")
                        .HasColumnType("float");

                    b.Property<double>("PriceForRent")
                        .HasColumnType("float");

                    b.Property<int>("ProducerID")
                        .HasColumnType("int");

                    b.Property<string>("ProducerName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("PublisherID")
                        .HasColumnType("int");

                    b.Property<string>("PublisherName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("Released")
                        .HasColumnType("int");

                    b.Property<int>("Runtime")
                        .HasColumnType("int");

                    b.Property<int>("SoldItems")
                        .HasColumnType("int");

                    b.Property<string>("Synopsis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(350)")
                        .HasMaxLength(350);

                    b.HasKey("Id");

                    b.HasIndex("DirectorID");

                    b.HasIndex("GenreID");

                    b.HasIndex("ProducerID");

                    b.HasIndex("PublisherID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = "$ 155–175 million",
                            Cast = "Tye Sheridan,Olivia Cooke,Ben Mendelsohn,T.J.Miller,Simon Pegg,Mark Rylance",
                            DirectorID = 1,
                            DirectorName = "Steven Spielberg",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            PhotoURL = "Ready_Player_One.png",
                            PriceForBuy = 19.989999999999998,
                            PriceForRent = 4.9900000000000002,
                            ProducerID = 1,
                            ProducerName = "Donald De Line",
                            PublisherID = 1,
                            PublisherName = "Warner Bros",
                            Released = 2018,
                            Runtime = 140,
                            SoldItems = 0,
                            Synopsis = "Ready Player One is a 2018 American science fiction adventure film directed by Steven Spielberg, from a screenplay by Zak Penn and Ernest Cline based on Cline's 2011 novel of the same name. It stars Tye Sheridan, Olivia Cooke, Ben Mendelsohn, T.J. Miller, Simon Pegg, and Mark Rylance. It takes place in 2045, when much of humanity uses the virtual reality software OASIS (Ontologically Anthropocentric Sensory Immersive Simulation) to escape the desolation of the real world. Orphaned teenager Wade Watts (Sheridan) finds clues to a hidden game that promises OASIS's ownership to the winner, and he and four allies try to complete it before a corporation run by businessman Nolan Sorrento (Mendelsohn) can do so.",
                            Title = "Ready Player One"
                        },
                        new
                        {
                            Id = 2,
                            Budget = "$ 159–200 million",
                            Cast = "Robert De Niro, Al Pacino, Joe Pesci,Ray Romano,Bobby Cannavale, Anna Paquin",
                            DirectorID = 2,
                            DirectorName = "Martin Scorsese",
                            GenreID = 6,
                            GenreName = "Crime & Thrillers",
                            PhotoURL = "The_Irishman.jpg",
                            PriceForBuy = 24.989999999999998,
                            PriceForRent = 4.9900000000000002,
                            ProducerID = 2,
                            ProducerName = "Robert De Niro",
                            PublisherID = 2,
                            PublisherName = "TriBeCa Productions",
                            Released = 2019,
                            Runtime = 209,
                            SoldItems = 0,
                            Synopsis = "The Irishman (titled onscreen as I Heard You Paint Houses) is a 2019 American epic crime film directed and produced by Martin Scorsese and written by Steven Zaillian, based on the 2004 nonfiction book I Heard You Paint Houses by Charles Brandt. It stars Robert De Niro, Al Pacino, and Joe Pesci, with Ray Romano, Bobby Cannavale, Anna Paquin, Stephen Graham, Stephanie Kurtzuba, Jesse Plemons, and Harvey Keitel in supporting roles. The film follows Frank Sheeran (De Niro), a truck driver who becomes a hitman involved with mobster Russell Bufalino (Pesci) and his crime family, including his time working for the powerful Teamster Jimmy Hoffa (Pacino).",
                            Title = "The Irishman"
                        },
                        new
                        {
                            Id = 3,
                            Budget = "$ 170–177 million",
                            Cast = "Chris Evans,Scarlett Johansson,Sebastian Stan,Anthony Mackie,Cobie Smulders,Frank Grillo,Emily VanCamp",
                            DirectorID = 3,
                            DirectorName = "Joe Russo",
                            GenreID = 1,
                            GenreName = "Action",
                            PhotoURL = "Captain_America_The_Winter_Soldier.jpg",
                            PriceForBuy = 19.989999999999998,
                            PriceForRent = 7.0,
                            ProducerID = 3,
                            ProducerName = "Kevin Feige",
                            PublisherID = 3,
                            PublisherName = "Marvel Studios",
                            Released = 2014,
                            Runtime = 136,
                            SoldItems = 0,
                            Synopsis = "In the film, Captain America joins forces with Black Widow and Falcon to uncover a conspiracy within the spy agency S.H.I.E.L.D. while facing a mysterious assassin known as the Winter Soldier. Markus and McFeely began writing the sequel around the release of The First Avenger in July 2011.The script draws from the Winter Soldier story arc in the comic books written by Ed Brubaker as well as conspiracy fiction from the 1970s such as Three Days of the Condor (1975). The film explores S.H.I.E.L.D., similarly to how the first film explored the U.S. military, after Rogers was shown working for the agency in the MCU crossover film The Avengers (2012).",
                            Title = "Captain America:The Winter Soldier"
                        },
                        new
                        {
                            Id = 4,
                            Budget = "$ 100-150 million",
                            Cast = "Fionn Whitehead,Tom Glynn - Carney,Jack Lowden,Harry Styles,Aneurin Barnard,James D'Arcy,Barry Keoghan",
                            DirectorID = 4,
                            DirectorName = "Christopher Nolan",
                            GenreID = 8,
                            GenreName = "Drama",
                            PhotoURL = "Dunkirk.jpg",
                            PriceForBuy = 24.989999999999998,
                            PriceForRent = 11.99,
                            ProducerID = 4,
                            ProducerName = "Emma Thomas",
                            PublisherID = 1,
                            PublisherName = "Warner Bross",
                            Released = 2017,
                            Runtime = 106,
                            SoldItems = 0,
                            Synopsis = "In 1940, during the Battle of France, Allied soldiers have retreated to Dunkirk. Tommy, a young British private, is the sole survivor of a German ambush. At the beach, he finds thousands of troops awaiting evacuation and meets Gibson, who is burying a body. After a Luftwaffe dive-bomber attack, they find a wounded man. They rush his stretcher onto a hospital ship, hoping to get aboard, but are ordered off. The ship is sunk by dive bombers; Tommy saves another soldier, Alex. They leave at night on a destroyer, but are torpedoed by a U-boat. Gibson saves Tommy and Alex from the sinking ship, and they get back to the beach.",
                            Title = "Dunkirk"
                        },
                        new
                        {
                            Id = 5,
                            Budget = "$ 90-96 million",
                            Cast = "Leonardo DiCaprio,Brad Pitt,Margot Robbie,Emile Hirsch,Margaret Qualley,Timothy Olyphant",
                            DirectorID = 5,
                            DirectorName = "Quentin Tarantino",
                            GenreID = 5,
                            GenreName = "Comedy",
                            PhotoURL = "Once_Upon_a_Time_in_Hollywood_poster.png",
                            PriceForBuy = 14.99,
                            PriceForRent = 7.9900000000000002,
                            ProducerID = 5,
                            ProducerName = "David Heyman",
                            PublisherID = 4,
                            PublisherName = "Columbia Pictures",
                            Released = 2019,
                            Runtime = 161,
                            SoldItems = 0,
                            Synopsis = "In February 1969, veteran Hollywood actor Rick Dalton (DiCaprio), star of 1950s Western television series Bounty Law, fears his career is waning. Casting agent Marvin Schwarz (Pacino) recommends he make Spaghetti Westerns in Italy, which Dalton feels are beneath him. Dalton's best friend and stunt double, Cliff Booth (Pitt)—a war veteran skilled in hand-to-hand combat[10] who lives in a tiny trailer with his pit bull, Brandy—drives Dalton around Los Angeles because Dalton's driver's license has been suspended due to DUI. Booth struggles to find stunt work in Hollywood because of rumors he murdered his wife. Actress Sharon Tate (Robbie) and her husband, director Roman Polanski (Zawierucha), have moved next door to Dalton. He dreams of befriending them to revive his declining acting career. That night, Tate and Polanski attend a celebrity-filled party at the Playboy Mansion.",
                            Title = " Once Upon a Time in Hollywood"
                        },
                        new
                        {
                            Id = 6,
                            Budget = "$ 3 million",
                            Cast = "Ethan Hawke,Julie Delpy, Seamus Davey-Fitzpatrick,Jennifer Prior",
                            DirectorID = 6,
                            DirectorName = "Richard Linklater",
                            GenreID = 10,
                            GenreName = "Romance",
                            PhotoURL = "Before_Midnight.jpg",
                            PriceForBuy = 9.9900000000000002,
                            PriceForRent = 4.9900000000000002,
                            ProducerID = 6,
                            ProducerName = "Christos V. Konstantakopoulos",
                            PublisherID = 5,
                            PublisherName = "Castle Rock Entertainment",
                            Released = 2013,
                            Runtime = 109,
                            SoldItems = 0,
                            Synopsis = "Before Midnight is a 2013 American romantic drama film, the third in a trilogy featuring two characters, following Before Sunrise (1995) and Before Sunset (2004).Nine years have passed since Before Sunset. Jesse and Céline have become a couple and parents to twin girls. Jesse struggles to maintain his relationship with his teenage son, Hank, who lives in Chicago with his mother, Jesse's ex-wife. Jesse is now a successful novelist, while Céline is at a career crossroads, considering a job with the French government. After Hank spends the summer with Jesse and Céline on the Greek Peloponnese peninsula, Jesse experiences a disconnect with Hank when he drops him off at the airport to fly home and reflects on his inability to be a good father to him.",
                            Title = "Before Midnight"
                        },
                        new
                        {
                            Id = 7,
                            Budget = "$ 150-185 million",
                            Cast = "Ryan Gosling,Harrison Ford,Ana de Armas,Sylvia Hoeks,Robin Wright,Mackenzie Davis",
                            DirectorID = 7,
                            DirectorName = "Denis Villeneuve",
                            GenreID = 11,
                            GenreName = "Sci-Fi",
                            PhotoURL = "Blade_Runner_2049.png",
                            PriceForBuy = 14.99,
                            PriceForRent = 7.9900000000000002,
                            ProducerID = 7,
                            ProducerName = "Broderick Johnson",
                            PublisherID = 4,
                            PublisherName = "Columbia Pictures",
                            Released = 2017,
                            Runtime = 163,
                            SoldItems = 0,
                            Synopsis = "In 2049, bioengineered humans known as replicants are slaves. K, a replicant, works for the Los Angeles Police Department (LAPD) as a blade runner,an officer who hunts and 'retires' (kills) rogue replicants. At a protein farm, he retires Sapper Morton and finds a box buried under a tree. The box contains the remains of a female replicant who died during a caesarean section, demonstrating that replicants can reproduce biologically, previously thought impossible. K's superior, Lt. Joshi, fears that this could lead to a war between humans and replicants. She orders K to find and retire the replicant child to hide the truth.",
                            Title = "Blade Runner 2049"
                        },
                        new
                        {
                            Id = 8,
                            Budget = "$ 90 million",
                            Cast = "Daniel Craig,Rooney Mara,Christopher Plummer,Stellan Skarsgård,Steven Berkoff",
                            DirectorID = 8,
                            DirectorName = "David Fincher",
                            GenreID = 6,
                            GenreName = "Crime & Thrillers",
                            PhotoURL = "The_Girl_with_the_Dragon_Tattoo.jpg",
                            PriceForBuy = 11.99,
                            PriceForRent = 4.9900000000000002,
                            ProducerID = 8,
                            ProducerName = "Scott Rudin",
                            PublisherID = 4,
                            PublisherName = "Columbia Pictures",
                            Released = 2011,
                            Runtime = 158,
                            SoldItems = 0,
                            Synopsis = "The Girl with the Dragon Tattoo is a 2011 psychological crime thriller film based on the 2005 novel by Swedish writer Stieg Larsson.In Stockholm, disgraced journalist Mikael Blomkvist is recovering from the legal and professional fallout of a libel suit brought against him by businessman Hans-Erik Wennerström, straining Blomkvist's relationship with his business partner and married lover, Erika Berger. Lisbeth Salander, a young, brilliant but antisocial investigator and hacker, compiles an extensive background check on Blomkvist for the wealthy Henrik Vanger, who offers Blomkvist evidence against Wennerström in exchange for an unusual task: investigate the 40-year-old disappearance and presumed murder of Henrik's grandniece, Harriet. Blomkvist agrees, and moves into a cottage on the Vanger family estate on Hedestad Island.",
                            Title = "The Girl with the Dragon Tattoo "
                        },
                        new
                        {
                            Id = 9,
                            Budget = "$ 150-175 million",
                            Cast = "Auliʻi Cravalho,Dwayne Johnson,Rachel House,Temuera Morrison,Jemaine Clement,Nicole Scherzinger",
                            DirectorID = 9,
                            DirectorName = " Ron Clements",
                            GenreID = 3,
                            GenreName = "Animation",
                            PhotoURL = "Moana.jpg",
                            PriceForBuy = 11.99,
                            PriceForRent = 4.9900000000000002,
                            ProducerID = 9,
                            ProducerName = "Osnat Shurer",
                            PublisherID = 6,
                            PublisherName = "Walt Disney Pictures",
                            Released = 2016,
                            Runtime = 107,
                            SoldItems = 0,
                            Synopsis = "On the Polynesian island of Motunui, the inhabitants worship the goddess Te Fiti, who brought life to the ocean using a pounamu stone as her heart and the source of her power. Maui, the shape-shifting demigod and master of sailing, steals the heart to give humanity the power of creation. However, Te Fiti disintegrates, and Maui is attacked by another who seeks the heart: Te Kā, a volcanic demon. Maui is blasted out of the sky, losing both his magical giant fishhook and the heart to the depths of the sea.",
                            Title = "Moana"
                        },
                        new
                        {
                            Id = 10,
                            Budget = "$ 140 million",
                            Cast = "Joseph Gordon-Levitt,Brian Murray,Emma Thompson",
                            DirectorID = 9,
                            DirectorName = " Ron Clements",
                            GenreID = 3,
                            GenreName = "Animation",
                            PhotoURL = "Treasure_Planet.jpg",
                            PriceForBuy = 9.9900000000000002,
                            PriceForRent = 4.9900000000000002,
                            ProducerID = 10,
                            ProducerName = "Roy Conli",
                            PublisherID = 6,
                            PublisherName = "Walt Disney Pictures",
                            Released = 2002,
                            Runtime = 95,
                            SoldItems = 0,
                            Synopsis = "On the planet Montressor, a young Jim Hawkins is enchanted by stories of the legendary pirate Captain Nathaniel Flint and his ability to appear from out of nowhere, raid passing ships, and disappear in order to hide the loot on the mysterious 'Treasure Planet'. Twelve years later, having been abandoned by his father at a young age, Jim has grown into an aloof and isolated troublemaker. He reluctantly helps his mother Sarah run the family's Benbow Inn, and derives amusement from 'Alponian solar cruising', skysurfing atop a rocket-powered sailboard.",
                            Title = "Treasure Planet"
                        },
                        new
                        {
                            Id = 11,
                            Budget = "$ 54 million",
                            Cast = "Owen Wilson,Kate Hudson,Matt Dillon,Seth Rogen",
                            DirectorID = 3,
                            DirectorName = "Joe Russo",
                            GenreID = 5,
                            GenreName = "Comedy",
                            PhotoURL = "Dupreeposter.jpg",
                            PriceForBuy = 9.9900000000000002,
                            PriceForRent = 4.9900000000000002,
                            ProducerID = 8,
                            ProducerName = "Scott Rudin",
                            PublisherID = 7,
                            PublisherName = "Universal Pictures",
                            Released = 2006,
                            Runtime = 109,
                            SoldItems = 0,
                            Synopsis = "Molly (Kate Hudson) and Carl (Matt Dillon) are preparing for their wedding day in Hawaii, until Carl's friend Neil (Seth Rogen) interrupts to say that Randolph Dupree (Owen Wilson) got lost. They drive off together to pick up Dupree, who appeared to have hitched a ride with a light plane after landing on the wrong island. A day before the wedding, Molly's father, Bob Thompson (Michael Douglas), who is also CEO of the company that Carl works for, makes a toast with rude jokes about Carl, foreshadowing a conflict between the two. Later at a pre-celebration at a bar, Carl neglects Dupree to be with Molly. Carl and Dupree later make up on the beach, as Dupree apologizes for laughing at Bob's jokes. Carl and Molly get married. When Carl returns to work, he is surprised to find that Bob has promoted him to be in charge of a design he proposed, though it had been altered somewhat.",
                            Title = "You, Me and Dupree"
                        },
                        new
                        {
                            Id = 12,
                            Budget = "$ 8 million",
                            Cast = "John Travolta,Samuel L.Jackson,Uma Thurman,Harvey Keitel,Tim Roth,Amanda Plummer",
                            DirectorID = 5,
                            DirectorName = "Quentin Tarantino",
                            GenreID = 6,
                            GenreName = "Crime & Thrillers",
                            PhotoURL = "Pulp_Fiction.jpg",
                            PriceForBuy = 12.99,
                            PriceForRent = 7.9900000000000002,
                            ProducerID = 11,
                            ProducerName = "Lawrence Bender",
                            PublisherID = 7,
                            PublisherName = "Universal Pictures",
                            Released = 1994,
                            Runtime = 154,
                            SoldItems = 0,
                            Synopsis = "Tarantino wrote Pulp Fiction in 1992 and 1993, incorporating scenes that Avary originally wrote for True Romance (1993). Its plot occurs out of chronological order. The film is also self-referential from its opening moments, beginning with a title card that gives two dictionary definitions of 'pulp'. Considerable screen time is devoted to monologues and casual conversations with eclectic dialogue revealing each character's perspectives on several subjects, and the film features an ironic combination of humor and strong violence. TriStar Pictures reportedly turned down the script as 'too demented'. Miramax co-chairman Harvey Weinstein was enthralled, however, and the film became the first that Miramax fully financed.",
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 13,
                            Budget = "$ 65 million",
                            Cast = "Daniel Day-Lewis,Sally Field,David Strathairn,Joseph Gordon - Levitt",
                            DirectorID = 1,
                            DirectorName = "Steven Spielberg",
                            GenreID = 8,
                            GenreName = "Drama",
                            PhotoURL = "Lincoln_2012.jpg",
                            PriceForBuy = 9.9900000000000002,
                            PriceForRent = 4.9900000000000002,
                            ProducerID = 12,
                            ProducerName = "Kathleen Kennedy",
                            PublisherID = 8,
                            PublisherName = "20th Century Fox",
                            Released = 2012,
                            Runtime = 150,
                            SoldItems = 0,
                            Synopsis = "In January 1865, United States President Abraham Lincoln expects the Civil War to end soon, with the defeat of the Confederate States. He is concerned that his 1863 Emancipation Proclamation may be discarded by the courts after the war, and the proposed Thirteenth Amendment will be defeated by the returning slave states. He feels it imperative to pass the amendment beforehand, to remove any possibility that freed slaves might be re-enslaved.",
                            Title = "Lincoln"
                        },
                        new
                        {
                            Id = 14,
                            Budget = "$ 52 million",
                            Cast = "Leonardo DiCaprio,Tom Hanks,Christopher Walken,Martin Sheen",
                            DirectorID = 1,
                            DirectorName = "Steven Spielberg",
                            GenreID = 6,
                            GenreName = "Crime & Thrillers",
                            PhotoURL = "CatchMeIfYouCan.jpg",
                            PriceForBuy = 9.9900000000000002,
                            PriceForRent = 4.9900000000000002,
                            ProducerID = 13,
                            ProducerName = "Walter F. Parkes",
                            PublisherID = 9,
                            PublisherName = "DreamWorks Pictures",
                            Released = 2002,
                            Runtime = 141,
                            SoldItems = 0,
                            Synopsis = "In 1963, teenager Frank Abagnale lives in New Rochelle, New York with his father Frank Abagnale, Sr., and French mother, Paula. When Frank Sr. encounters tax problems with the IRS, his family is forced to move from their large home to a small apartment. Paula carries on an affair with Jack Barnes, her husband's friend. Meanwhile, Frank has to transfer to public school and gets into trouble when he begins posing as a substitute French teacher on his first day there. Frank runs away when his parents divorce. Needing money, he turns to confidence scams to survive, and his cons grow bolder. He impersonates an airline pilot and forges Pan Am payroll checks. Soon, his forgeries are worth millions of dollars.",
                            Title = "Catch Me If You Can"
                        });
                });

            modelBuilder.Entity("MovieStore.Data.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("MovieStore.Data.Entities.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Popularity")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Producers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Donald De Line",
                            Popularity = true
                        },
                        new
                        {
                            Id = 2,
                            Name = "Robert De Niro",
                            Popularity = true
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kevin Feige",
                            Popularity = false
                        },
                        new
                        {
                            Id = 4,
                            Name = "Emma Thomas",
                            Popularity = true
                        },
                        new
                        {
                            Id = 5,
                            Name = "David Heyman",
                            Popularity = true
                        },
                        new
                        {
                            Id = 6,
                            Name = "Christos V. Konstantakopoulos",
                            Popularity = false
                        },
                        new
                        {
                            Id = 7,
                            Name = "Broderick Johnson",
                            Popularity = true
                        },
                        new
                        {
                            Id = 8,
                            Name = "Scott Rudin",
                            Popularity = true
                        },
                        new
                        {
                            Id = 9,
                            Name = "  Osnat Shurer",
                            Popularity = true
                        },
                        new
                        {
                            Id = 10,
                            Name = "Roy Conli",
                            Popularity = true
                        },
                        new
                        {
                            Id = 11,
                            Name = "Lawrence Bender",
                            Popularity = false
                        },
                        new
                        {
                            Id = 12,
                            Name = "Kathleen Kennedy",
                            Popularity = true
                        },
                        new
                        {
                            Id = 13,
                            Name = "Walter F.Parkes",
                            Popularity = true
                        });
                });

            modelBuilder.Entity("MovieStore.Data.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Name = "Warner Bros"
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            Name = "TriBeCa Productions"
                        },
                        new
                        {
                            Id = 3,
                            Country = "USA",
                            Name = "Marvel Studios"
                        },
                        new
                        {
                            Id = 4,
                            Country = "USA",
                            Name = "Columbia Pictures"
                        },
                        new
                        {
                            Id = 5,
                            Country = "USA",
                            Name = "Castle Rock Entertainment"
                        },
                        new
                        {
                            Id = 6,
                            Country = "USA",
                            Name = "Walt Disney Pictures"
                        },
                        new
                        {
                            Id = 7,
                            Country = "USA",
                            Name = " Universal Pictures"
                        },
                        new
                        {
                            Id = 8,
                            Country = "USA",
                            Name = "20th Century Fox"
                        },
                        new
                        {
                            Id = 9,
                            Country = "USA",
                            Name = " DreamWorks Pictures"
                        });
                });

            modelBuilder.Entity("MovieStore.Data.Entities.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("MovieStore.Data.Entities.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("ProducerId")
                        .HasColumnType("int");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieStore.Data.Entities.Movie", b =>
                {
                    b.HasOne("MovieStore.Data.Entities.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieStore.Data.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieStore.Data.Entities.Producer", "Producer")
                        .WithMany("Movies")
                        .HasForeignKey("ProducerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieStore.Data.Entities.Publisher", "Publisher")
                        .WithMany("Movies")
                        .HasForeignKey("PublisherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieStore.Data.Entities.Photo", b =>
                {
                    b.HasOne("MovieStore.Data.Entities.Movie", null)
                        .WithMany("Photos")
                        .HasForeignKey("MovieId");
                });
#pragma warning restore 612, 618
        }
    }
}
